Algoritmo "Transformação de velocidade"
var
velocidade:real
metros:real
temp:real
INICIO
Escreva(" Você percorreu quantos metros: ")
leia(metros)
escreva(" Você percorreu por quantos segundos: ")
leia(temp)
velocidade <- (metros/temp)* 3.6
escreval(" a sua velocidade em Km/h é: ", velocidade)
Fimalgoritmo
{11) Faça um algoritmo que transforme uma
velocidade fornecida em m/s pelo usuário
para Km/h. Para tal, multiplique o valor em
m/s por 3,6.}